Refactor storehouse client
kytos/topology pull request #114
Opened 2020-06-22 15:29 UTC by cmagnobarbosa

Today, the storehouse client is very generic and the info/debug messages provide
low-level information. This commit starts to solve this problem, improving
informational messages and changing the method names.

Related:
- #113

2020-07-15 19:02 UTC, josemauro requested changes

2020-07-15 19:02 UTC, josemauro commented on main.py
> +                     " to enabled.")
```suggestion
            log.info(f"Storing administrative state from switch {dpid}"
                     " to enabled.")
```

2020-07-15 19:02 UTC, josemauro commented on main.py
> +                     " to disabled.")
```suggestion
            log.info(f"Storing administrative state from switch {dpid}"
                     " to disabled.")
```

2020-07-15 19:02 UTC, josemauro commented on main.py
> +            log.info(f"Storing administrative changes enabling interfaces.")
```suggestion
            log.info(f"Storing administrative state for enabled interfaces.")
```

2020-07-15 19:02 UTC, josemauro commented on main.py
> +            log.info(f"Storing administrative changes disabling interfaces.")
```suggestion
            log.info(f"Storing administrative state for disabled interfaces.")
```

2020-07-15 20:33 UTC, josemauro approved these changes

2020-07-21 15:30 UTC, ajoaoff approved these changes

2020-07-23 17:52 UTC, hdiogenes commented on storehouse.py
> +        log.info(f'Administratively changes was stored in {self.namespace}.')
```suggestion
        log.info(f'Network administrative status saved in {self.namespace}.{data.box_id}')
```

2020-07-23 18:23 UTC, merged